#!/bin/bash
set -e

# ADS Registry TCP Tuning Script
# Optimizes OS-level TCP settings for handling large container image uploads/downloads
# Run with sudo: sudo ./scripts/tune-tcp.sh

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() {
    echo -e "${BLUE}[*]${NC} $1"
}

success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1"
    exit 1
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    error "This script must be run as root (use sudo)"
fi

# Detect OS
OS_TYPE=$(uname -s)
log "Detected OS: $OS_TYPE"

if [ "$OS_TYPE" != "Linux" ]; then
    warn "This script is optimized for Linux. Some settings may not apply to $OS_TYPE"
fi

# Backup current sysctl settings
BACKUP_FILE="/etc/sysctl.d/99-ads-registry-backup-$(date +%Y%m%d-%H%M%S).conf"
log "Backing up current TCP settings to $BACKUP_FILE..."
sysctl -a | grep -E "net\.(core|ipv4)" > "$BACKUP_FILE" 2>/dev/null || true
success "Backup created"

# Apply TCP tuning for large image transfers
log "Applying TCP tuning for large container images..."

cat > /etc/sysctl.d/99-ads-registry-tcp-tuning.conf <<'EOF'
# ADS Registry TCP Tuning Configuration
# Optimized for handling large container image uploads/downloads
# Generated by tune-tcp.sh

# ============================================================================
# TCP Buffer Sizes (Critical for large file transfers)
# ============================================================================

# Increase max socket buffer sizes (128MB)
# This allows TCP windows to scale up for high-bandwidth, high-latency connections
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728

# Increase default and max TCP buffer sizes
# Format: min default max (in bytes)
# Default: 4KB, 128KB, 128MB - allows auto-tuning up to 128MB
net.ipv4.tcp_rmem = 4096 131072 134217728
net.ipv4.tcp_wmem = 4096 131072 134217728

# Increase the maximum amount of option memory buffers (for TCP options)
net.core.optmem_max = 65536

# ============================================================================
# Connection Queue Settings
# ============================================================================

# Increase the maximum number of connection requests queued
# Helps handle burst traffic during multiple simultaneous image pushes
net.core.somaxconn = 4096
net.ipv4.tcp_max_syn_backlog = 8192

# Increase the maximum number of packets queued on the input side
net.core.netdev_max_backlog = 16384

# ============================================================================
# TCP Connection Settings
# ============================================================================

# Enable TCP window scaling (required for buffers > 64KB)
# This is essential for high-bandwidth transfers
net.ipv4.tcp_window_scaling = 1

# Enable TCP timestamps (helps with round-trip time measurement)
net.ipv4.tcp_timestamps = 1

# Enable selective acknowledgments (SACK)
# Improves performance when packets are lost
net.ipv4.tcp_sack = 1

# Disable TCP slow start after idle
# Prevents bandwidth drop when connection goes idle during large transfers
net.ipv4.tcp_slow_start_after_idle = 0

# ============================================================================
# TCP Keepalive Settings
# ============================================================================

# Reduce keepalive probe interval to detect dead connections faster
# Prevents hanging connections that can block resources
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 6

# ============================================================================
# TCP Reuse and Recycling
# ============================================================================

# Allow reuse of TIME_WAIT sockets for new connections
# Helps prevent port exhaustion with many connections
net.ipv4.tcp_tw_reuse = 1

# Increase the range of local ports available
# Default is often 32768-60999, we expand to 10000-65535
net.ipv4.ip_local_port_range = 10000 65535

# ============================================================================
# Memory Pressure Settings
# ============================================================================

# Increase TCP memory allocation
# Format: min pressure max (in pages, typically 4KB each)
# This allows ~1GB, ~1.5GB, ~2GB for TCP memory
net.ipv4.tcp_mem = 262144 393216 524288

# ============================================================================
# Congestion Control (Optional - Linux 4.9+)
# ============================================================================

# Use BBR congestion control if available (better for high-latency networks)
# BBR provides better throughput and lower latency than CUBIC
# Note: Requires kernel 4.9+ and tcp_bbr module
# Uncomment if your kernel supports it:
# net.core.default_qdisc = fq
# net.ipv4.tcp_congestion_control = bbr

# ============================================================================
# File Descriptor Limits
# ============================================================================

# Increase system-wide file descriptor limit
fs.file-max = 2097152

# Increase inotify limits (useful for monitoring file changes)
fs.inotify.max_user_watches = 524288
fs.inotify.max_user_instances = 512

EOF

success "TCP tuning configuration written to /etc/sysctl.d/99-ads-registry-tcp-tuning.conf"

# Apply the settings
log "Applying sysctl settings..."
if sysctl -p /etc/sysctl.d/99-ads-registry-tcp-tuning.conf; then
    success "TCP tuning settings applied successfully"
else
    error "Failed to apply TCP tuning settings"
fi

# Check if BBR is available
log "Checking for BBR congestion control availability..."
if [ -f /proc/sys/net/ipv4/tcp_available_congestion_control ]; then
    AVAIL_CC=$(cat /proc/sys/net/ipv4/tcp_available_congestion_control)
    if echo "$AVAIL_CC" | grep -q "bbr"; then
        warn "BBR is available but not enabled. To enable BBR, uncomment the BBR lines in the config and reapply."
        warn "Run: sudo nano /etc/sysctl.d/99-ads-registry-tcp-tuning.conf"
        warn "Then: sudo sysctl -p /etc/sysctl.d/99-ads-registry-tcp-tuning.conf"
    else
        log "BBR not available on this kernel (requires 4.9+)"
    fi
fi

# Update ulimits
log "Updating file descriptor limits..."
cat > /etc/security/limits.d/99-ads-registry.conf <<'EOF'
# ADS Registry file descriptor limits
# Allows the registry to handle many concurrent connections

*               soft    nofile          65536
*               hard    nofile          65536
root            soft    nofile          65536
root            hard    nofile          65536

# For specific registry user (if running as non-root)
registry        soft    nofile          65536
registry        hard    nofile          65536
EOF

success "File descriptor limits configured in /etc/security/limits.d/99-ads-registry.conf"

# Display current settings
echo ""
echo "=========================================="
echo "  TCP Tuning Complete!"
echo "=========================================="
echo ""
log "Current TCP settings:"
echo ""
echo "Buffer Sizes:"
sysctl net.core.rmem_max net.core.wmem_max
sysctl net.ipv4.tcp_rmem
sysctl net.ipv4.tcp_wmem
echo ""
echo "Connection Settings:"
sysctl net.core.somaxconn
sysctl net.ipv4.tcp_max_syn_backlog
echo ""
echo "Keepalive Settings:"
sysctl net.ipv4.tcp_keepalive_time
sysctl net.ipv4.tcp_keepalive_intvl
sysctl net.ipv4.tcp_keepalive_probes
echo ""
echo "Congestion Control:"
sysctl net.ipv4.tcp_congestion_control 2>/dev/null || echo "net.ipv4.tcp_congestion_control = (not available)"
echo ""
warn "Note: Changes are immediate but will be lost on reboot unless sysctl files persist."
warn "The configuration file /etc/sysctl.d/99-ads-registry-tcp-tuning.conf will be loaded on boot."
echo ""
log "To revert changes, restore from backup:"
echo "  sudo sysctl -p $BACKUP_FILE"
echo ""
success "TCP tuning complete! Restart the registry to ensure all settings take effect."
